FROM python:3.6.7

ENV PYTHONUNBUFFERED 1

# Install OpenJDK-8
RUN apt-get update && \
    apt-get install -y openjdk-8-jdk && \
    apt-get install -y ant && \
    apt-get clean;

# Fix certificate issues
RUN apt-get update && \
    apt-get install ca-certificates-java && \
    apt-get clean && \
    update-ca-certificates -f;

# Setup JAVA_HOME -- useful for docker commandline
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/
RUN export JAVA_HOME

RUN mkdir /code

COPY ./django-app/requirements.txt /code/

RUN pip install --no-cache-dir -r /code/requirements.txt

COPY ./django-app /code

WORKDIR /code/

RUN chmod +x entrypoint*.sh
