FROM python:3.6.7

ENV PYTHONUNBUFFERED 1

RUN mkdir /code

COPY ./django-app/requirements.txt /code/

RUN pip install --no-cache-dir -r /code/requirements.txt

COPY ./django-app /code

WORKDIR /code/

RUN chmod +x entrypoint*.sh
