# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-08 21:40
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tickets', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, default=list, null=True, size=None)),
                ('purchase_date', models.DateTimeField()),
                ('carrier', models.CharField(blank=True, default='', max_length=128)),
                ('start_time', models.DateTimeField()),
                ('finish_time', models.DateTimeField()),
                ('start_place', models.CharField(blank=True, default='', max_length=128)),
                ('finish_place', models.CharField(blank=True, default='', max_length=128)),
                ('car_class', models.IntegerField(blank=True, default=2)),
                ('stops', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, default=list, null=True, size=None)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('seats', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, default=list, null=True, size=None)),
                ('train_number', models.CharField(blank=True, default='', max_length=128)),
                ('car_number', models.IntegerField(blank=True, default=None, null=True)),
                ('total_length', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
    ]
