# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-08 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='qr_code',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='QR Code'),
        ),
    ]
