# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-09 00:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_ticket_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
