# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-09 11:20
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_ticket_car_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='closed_station_at_arrival',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='car_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
    ]
